version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8088:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress:/var/www/html
            - $PWD:/var/www/html/wp-content/plugins/wp-document-revisions

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8089:80
        environment:
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_ROOT_PASSWORD: '1'

volumes:
    wordpress:
    db:
