#!/bin/sh

set -e

export PATH="$HOME/.composer/vendor/bin:./bin:$PATH"

echo "Running unit tests..."
phpunit

echo "Running Style checks..."
phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
phpcs --standard=phpcs.ruleset.xml -p --colors *.php */**.php
