#!/bin/sh

set -e

export PATH="./vendor/squizlabs/php_codesniffer/bin:$PATH"

phpcs --config-set installed_paths ./vendor/wp-coding-standards/wpcs
phpcs --standard=phpcs.ruleset.xml -p -s --colors *.php */**.php -v
