#!/bin/sh

set -e

export PATH="$HOME/.composer/vendor/bin:./bin:$PATH"

echo "Running unit tests..."
phpunit

echo "Running Style checks..."
phpcs --config-set installed_paths ../../wp-coding-standards/wpcs
phpcs --standard=phpcs.ruleset.xml --colors $(find . -name '*.php' -not -path "./vendor/*")
