name: Generate POT file

on:
  push:
    branches:
      - main
      - master
    paths: 
      - "*.php"
  workflow_dispatch: {}

jobs:
  generate-pot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install WP-POT-CLI
        run: npm install --global wp-pot-cli

      - name: Generate POT file
        run: script/generate-pot

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            commit-message: "Update POT file"
            branch: update-pull-request/pot
            title: "Update POT file"
