name: Generate POT file

on:
    push:
        branches:
            - main
            - master
        paths:
            - '*.php'
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    generate-pot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: composer
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Generate POT file
              run: bash script/generate-pot

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  commit-message: 'Update POT file'
                  branch: update-pull-request/pot
                  title: 'Update POT file'
